/* Author:  Leonardo Trevisan Silio
 * Date:    07/02/2025
 */
using System.Collections.Generic;

namespace Orkestra.Extensions.VSCode;

/// <summary>
/// Represents a change log file.
/// </summary>
public class Changelog : List<Changelog.Version>
{
    public void Add(string title, string text)
        => Add(new Version(title, text));

    public record Version(string Title, string Text);

    public static Changelog Default => [
        new Version("Version 1.0.0", "All elements auto generated by Orkestra framework.")
    ];
}