/* Author:  Leonardo Trevisan Silio
 * Date:    11/06/2023
 */
using System;
using System.IO;
using System.Threading.Tasks;

namespace Orkestra.Extensions.VSCode;

public class VSCodeExtension : Extension
{
    public override async Task Generate(ExtensionArguments args)
    {
        var path = createTempFolder();
        await addPackageJson(path, args);
        await addReadme(path, args);
        await addLangConfiguration(path, args);
        await addExtensionJS(path, args);
        await addChangeLog(path, args);
        await addSyntaxes(path, args);
        await zip(path, args.Name + ".vsix");
        await install(path, args.Name + ".vsix");
    }

    async Task addPackageJson(string dict, ExtensionArguments args)
    {
        const string file = "package.json";
        var sw = open(dict, file);

        var name = args.Name;

        await sw.WriteAsync(
            $$"""
            {
                "name": "{{name}}"
                "displayName": "{{name}}",
                "description": "A autogenerated Orkestra VSCode extension of {{name}}.",
                "version": "1.0.0",
                "engines": {
                    "vscode": "^1.89.0"
                },
                "categories": [
                    "Programming Languages"
                ],
                "activationEvents": [],
                "main": "./extension.js",
                "contributes": {
            """
        );

        await sw.WriteAsync(
            """
                    "commands": [],
                    "languages": [],
                    "grammars": [],
            """
        );

        await sw.WriteAsync(
            """
                },                
                "scripts": {
                    "lint": "eslint .",
                    "pretest": "npm run lint",
                    "test": "vscode-test"
                },
                "devDependencies": {
                    "@types/vscode": "^1.89.0",
                    "@types/mocha": "^10.0.6",
                    "@types/node": "18.x",
                    "eslint": "^8.57.0",
                    "typescript": "^5.4.5",
                    "@vscode/test-cli": "^0.0.9",
                    "@vscode/test-electron": "^2.4.0"
                }
            }
            """
        );

        sw.Close();
    }

    async Task addReadme(string dict, ExtensionArguments args)
    {

    }

    async Task addLangConfiguration(string dict, ExtensionArguments args)
    {

    }

    async Task addExtensionJS(string dict, ExtensionArguments args)
    {

    }

    async Task addChangeLog(string dict, ExtensionArguments args)
    {

    }

    async Task addSyntaxes(string dict, ExtensionArguments args)
    {

    }

    async Task zip(string dict, string output)
    {

    }

    async Task install(string dict, string file)
    {

    }

    StreamWriter open(string folder, string file)
    {
        var path = Path.Combine(folder, file);
        var sw = new StreamWriter(path);
        return sw;
    }

    string createTempFolder()
    {
        var path = getRandomTempFile();
        initFolder(path);
        return path;
    }

    string getRandomTempFile()
    {
        var temp = Path.GetTempFileName();
        var guid = Guid.NewGuid().ToString();
        var path = Path.Combine(temp, guid);
        return path;
    }

    void initFolder(string path)
    {
        deleteIfExists(path);
        createFile(path);
    }

    void deleteIfExists(string path)
    {
        if (!Path.Exists(path))
            return;

        var dict = new DirectoryInfo(path);
        dict.Delete(true);
    }

    void createFile(string path)
        => Directory.CreateDirectory(path);
}